### ISSUE TITLE
一些bug和适配

### ISSUE THREAD

**Issue by mugzx** [MintCoolMC/MCBE_RainbowPieUI2#21]
1.21更新了合成器，能适配一下ui吗
另外复制世界的ui貌似没了
![Screenshot_2024-02-17-12-49-46-87_5c8300b655012b1930f2e0a7b81bf6a9.jpg](https://github.com/MintCoolMC/MCBE_RainbowPieUI2/assets/158086960/b347da42-7c9f-4c3b-a820-0cb90cfc5875)

**Comment by MintCoolMC** [comment]
合成器的界面截個圖我看看

**Comment by Moonslylr** [comment]
> 合成器的界面截個圖我看看

![Screenshot_2024-02-17-13-59-06-90.jpg](https://github.com/MintCoolMC/MCBE_RainbowPieUI2/assets/158086960/5bf387a6-c20a-4e36-a010-298667558fdb)

**Comment by MintCoolMC** [comment]
> > 合成器的界面截個圖我看看
> 
> ![Screenshot_2024-02-17-13-59-06-90.jpg](https://private-user-images.githubusercontent.com/158086960/305601225-5bf387a6-c20a-4e36-a010-298667558fdb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNTI5MTEsIm5iZiI6MTcwODE1MjYxMSwicGF0aCI6Ii8xNTgwODY5NjAvMzA1NjAxMjI1LTViZjM4N2E2LWMyMGEtNGUzNi1hMDEwLTI5ODY2NzU1OGZkYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxN1QwNjUwMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTVhMzUwNzA5YzI0YmZmOTA5ZmNmODYyZGQyYTZlZGQ1YmE0MmI5ZGI2NzRhYjlkYzQ4ZTUyODEwZjJkODQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pNGkFL6OGNEtzwfPW7wP7LR1k1sCI5ZwBZ6-rKOoqDY)

我等正式版更新再適配

**Comment by MintCoolMC** [comment]
> 1.21更新了合成器，能适配一下ui吗 另外复制世界的ui貌似没了 ![Screenshot_2024-02-17-12-49-46-87_5c8300b655012b1930f2e0a7b81bf6a9.jpg](https://private-user-images.githubusercontent.com/158086960/305598314-b347da42-7c9f-4c3b-a820-0cb90cfc5875.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMTY0NjksIm5iZiI6MTcwODIxNjE2OSwicGF0aCI6Ii8xNTgwODY5NjAvMzA1NTk4MzE0LWIzNDdkYTQyLTdjOWYtNGMzYi1hODIwLTBjYjkwY2ZjNTg3NS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOFQwMDI5MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzZmNWYyZWRjOTI4YTE2MTNkNjVlZTA4M2E3OWIwNGQyOGRiYzQ5YzE5MzNjOWFhZjYzYTUyYTA3ZGY2ODNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.H4Dak9os_JJ8LZ9SRheU1zS9x4vmp4NmFKglckdSjas)

![image](https://github.com/MintCoolMC/MCBE_RainbowPieUI2/assets/124319497/8ab0f079-37c7-4939-bb6e-cf4028be1676)
