### ISSUE TITLE
HUD界面的title背景常显示的错误

### ISSUE THREAD

**Issue by OoGodStaroO** [MintCoolMC/MCBE_RainbowPieUI2#32]
Rainbow Pie UI版本: v2.6.10133.HEAD_Release
游戏版本: 1.21.0.03
错误截图: 
![Screenshot_2024-07-13-14-08-13-285_com mojang minecraftpe](https://github.com/user-attachments/assets/a4d4d993-66c7-4652-bc83-77ab46d29131)
(此错误在游玩小游戏服务器的时候尤其烦人www)
更正后的hud文件(删除了title背景):
[hud_screen.json](https://github.com/user-attachments/files/16201148/hud_screen.json)

**Comment by SunshinePonyUwU** [comment]
可以提供一下復現方式嗎

**Comment by MintCoolMC** [comment]
抱歉剛剛切錯賬，我想知道你是否有設置圖中選項為100%
![Screenshot_20240713-144726_Minecraft](https://github.com/user-attachments/assets/33833018-51a5-4ccb-914f-13a886b942be)

**Comment by OoGodStaroO** [comment]
不好意思忘了有这茬（
