### ISSUE TITLE
Minecraft1.21.21 Rainbow Pie2.6.10133 Report an error

### ISSUE THREAD

**Issue by MorningStarsX** [MintCoolMC/MCBE_RainbowPieUI2#34]
Question:ui/pdp_screen.json：Unable to find handle：realms_plus_expiration/text
![Screenshot_20240820_105007_com mojang minecraftpe patch](https://github.com/user-attachments/assets/484a4b7c-bfba-4d0c-8950-fa304657583c)

**Comment by MintCoolMC** [comment]
Please use the version in actions before is released.
https://github.com/MintCoolMC/MCBE_RainbowPieUI2/actions/runs/10458423258
