### ISSUE TITLE
help

### ISSUE THREAD

**Issue by DoctorL06** [MintCoolMC/MCBE_RainbowPieUI2#44]
This link is invalid.
https://github.com/MintCoolMC/MCBE_RainbowPieUI2/actions/runs/11881039439

**Comment by DoctorL06** [comment]
![Uploading Screenshot_20241210_091736_mark.via.jpg…]()

**Comment by DoctorL06** [comment]
![Uploading Screenshot_20241210_091736_mark.via.jpg…]()

**Comment by DoctorL06** [comment]
![Screenshot_20241210_091736_mark via](https://github.com/user-attachments/assets/e5b30fb9-abac-4ab6-b668-f6777f0604c5)

**Comment by MintCoolMC** [comment]
Sorry I forget, this now moved to
https://github.com/MintCoolMC/MCBE_RainbowPieUI2/discussions/42
