### ISSUE TITLE
[功能添加]增加一个显示fps的模块

### ISSUE THREAD

**Issue by winner8877** [MintCoolMC/MCBE_RainbowPieUI2#45]
之前的fps显示都是21年的东西了，用着个这个ui有冲突，物品栏会消失

**Comment by MintCoolMC** [comment]
可以傳一下你使用的fps顯示嗎

**Comment by winner8877** [comment]
https://mcpedl.com/fps-counter-pack/

**Comment by winner8877** [comment]
[Uploading FPSCounter.mcpack…]()

**Comment by MintCoolMC** [comment]
看起來這個資源包的hud兼容性很差，並不是Rainbow Pie UI的問題

**Comment by MintCoolMC** [comment]
我有時間可以為你改一個兼容性好一些的fps顯示

**Comment by winner8877** [comment]
谢谢啦
